name: cicd

on: 
  push:
    branches: 
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: |
          npm install
          npm run build
      
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ALIYUN_HOST }}
          username: ${{ secrets.ALIYUN_USER }}
          password: ${{ secrets.ALIYUN_PASSWORD }}
          script: bash /ppap/del.sh
      
      # - name: copy file via ssh password
      #   uses: appleboy/scp-action@master
      #   with:
      #     host: ${{ secrets.ALIYUN_HOST }}
      #     username: ${{ secrets.ALIYUN_USER }}
      #     password: ${{ secrets.ALIYUN_PASSWORD }}
      #     source: "./dist/static, ./dist/index.html"
      #     target: ${{ secrets.ALIYUN_PPAPLIVE_PATH}}
      - name: Upload ftp
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.ALIYUN_HOST }}
          user: ${{ secrets.ALIYUN_USER }}
          password: ${{ secrets.ALIYUN_PASSWORD }}
          localDir: "dist/"
          remoteDir: ${{ secrets.ALIYUN_PPAPLIVE_PATH}}